import type { PublicTeam } from "@/app/api/teams/route";

export const MOCK_12_TEAMS: PublicTeam[] = [
  {
    id: "mock-team-1",
    team_name: "Rantharu",
    batch: "2nd Year",
    captain_name: "Nobody",
    captain_email: "nobody@susl.ac.lk",
    captain_contact: "+94771234567",
    player_count: 11,
    female_count: 2,
    registered_at: "2026-02-01T10:00:00.000Z",
    group_name: "Group A",
    has_logo: false,
    players: [
      { position: 1, fullName: "Nobody (C)", studentId: "SUSL/FOC/2Y/2026/001", gender: "male" },
      { position: 2, fullName: "Kavindu Chamith", studentId: "SUSL/FOC/2Y/2026/002", gender: "male" },
      { position: 3, fullName: "Sahan Perera", studentId: "SUSL/FOC/2Y/2026/003", gender: "male" },
      { position: 4, fullName: "Nuwan Silva", studentId: "SUSL/FOC/2Y/2026/004", gender: "male" },
      { position: 5, fullName: "Kasun Fernando", studentId: "SUSL/FOC/2Y/2026/005", gender: "male" },
      { position: 6, fullName: "Dilshan Jayasuriya", studentId: "SUSL/FOC/2Y/2026/006", gender: "male" },
      { position: 7, fullName: "Pathum Nissanka", studentId: "SUSL/FOC/2Y/2026/007", gender: "male" },
      { position: 8, fullName: "Charith Asalanka", studentId: "SUSL/FOC/2Y/2026/008", gender: "male" },
      { position: 9, fullName: "Wanindu Hasaranga", studentId: "SUSL/FOC/2Y/2026/009", gender: "male" },
      { position: 10, fullName: "Ama Perera", studentId: "SUSL/FOC/2Y/2026/010", gender: "female" },
      { position: 11, fullName: "Kavindi Silva", studentId: "SUSL/FOC/2Y/2026/011", gender: "female" },
    ],
  },
  {
    id: "mock-team-2",
    team_name: "Apex Predators",
    batch: "1st Year",
    captain_name: "Alice Johnson",
    captain_email: "alice@susl.ac.lk",
    captain_contact: "+94772345678",
    player_count: 11,
    female_count: 3,
    registered_at: "2026-02-01T10:30:00.000Z",
    group_name: "Group B",
    has_logo: false,
    players: [
      { position: 1, fullName: "Alice Johnson (C)", studentId: "SUSL/FOC/1Y/2026/012", gender: "female" },
      { position: 2, fullName: "Bob Smith", studentId: "SUSL/FOC/1Y/2026/013", gender: "male" },
      { position: 3, fullName: "Charlie Davis", studentId: "SUSL/FOC/1Y/2026/014", gender: "male" },
      { position: 4, fullName: "David Miller", studentId: "SUSL/FOC/1Y/2026/015", gender: "male" },
      { position: 5, fullName: "Eric Cantona", studentId: "SUSL/FOC/1Y/2026/016", gender: "male" },
      { position: 6, fullName: "Frank Lampard", studentId: "SUSL/FOC/1Y/2026/017", gender: "male" },
      { position: 7, fullName: "Gareth Bale", studentId: "SUSL/FOC/1Y/2026/018", gender: "male" },
      { position: 8, fullName: "Harry Kane", studentId: "SUSL/FOC/1Y/2026/019", gender: "male" },
      { position: 9, fullName: "Ian Rush", studentId: "SUSL/FOC/1Y/2026/020", gender: "male" },
      { position: 10, fullName: "Jenny Taylor", studentId: "SUSL/FOC/1Y/2026/021", gender: "female" },
      { position: 11, fullName: "Karen Gillan", studentId: "SUSL/FOC/1Y/2026/022", gender: "female" },
    ],
  },
  {
    id: "mock-team-3",
    team_name: "Byte Force",
    batch: "3rd Year",
    captain_name: "Charlie Brown",
    captain_email: "charlie@susl.ac.lk",
    captain_contact: "+94773456789",
    player_count: 11,
    female_count: 4,
    registered_at: "2026-02-01T11:00:00.000Z",
    group_name: "Group C",
    has_logo: false,
    players: [
      { position: 1, fullName: "Charlie Brown (C)", studentId: "SUSL/FOC/3Y/2026/023", gender: "male" },
      { position: 2, fullName: "Lucy van Pelt", studentId: "SUSL/FOC/3Y/2026/024", gender: "female" },
      { position: 3, fullName: "Linus van Pelt", studentId: "SUSL/FOC/3Y/2026/025", gender: "male" },
      { position: 4, fullName: "Snoopy Dog", studentId: "SUSL/FOC/3Y/2026/026", gender: "male" },
      { position: 5, fullName: "Woodstock Bird", studentId: "SUSL/FOC/3Y/2026/027", gender: "male" },
      { position: 6, fullName: "Schroeder Piano", studentId: "SUSL/FOC/3Y/2026/028", gender: "male" },
      { position: 7, fullName: "Peppermint Patty", studentId: "SUSL/FOC/3Y/2026/029", gender: "female" },
      { position: 8, fullName: "Marcie Carlin", studentId: "SUSL/FOC/3Y/2026/030", gender: "female" },
      { position: 9, fullName: "Franklin Armstrong", studentId: "SUSL/FOC/3Y/2026/031", gender: "male" },
      { position: 10, fullName: "Pig-Pen Miller", studentId: "SUSL/FOC/3Y/2026/032", gender: "male" },
      { position: 11, fullName: "Sally Brown", studentId: "SUSL/FOC/3Y/2026/033", gender: "female" },
    ],
  },
  {
    id: "mock-team-4",
    team_name: "Cyber Knights",
    batch: "4th Year",
    captain_name: "Diana Prince",
    captain_email: "diana@susl.ac.lk",
    captain_contact: "+94774567890",
    player_count: 11,
    female_count: 3,
    registered_at: "2026-02-01T11:30:00.000Z",
    group_name: "Group D",
    has_logo: false,
    players: [
      { position: 1, fullName: "Diana Prince (C)", studentId: "SUSL/FOC/4Y/2026/034", gender: "female" },
      { position: 2, fullName: "Bruce Wayne", studentId: "SUSL/FOC/4Y/2026/035", gender: "male" },
      { position: 3, fullName: "Clark Kent", studentId: "SUSL/FOC/4Y/2026/036", gender: "male" },
      { position: 4, fullName: "Barry Allen", studentId: "SUSL/FOC/4Y/2026/037", gender: "male" },
      { position: 5, fullName: "Hal Jordan", studentId: "SUSL/FOC/4Y/2026/038", gender: "male" },
      { position: 6, fullName: "Arthur Curry", studentId: "SUSL/FOC/4Y/2026/039", gender: "male" },
      { position: 7, fullName: "Victor Stone", studentId: "SUSL/FOC/4Y/2026/040", gender: "male" },
      { position: 8, fullName: "Oliver Queen", studentId: "SUSL/FOC/4Y/2026/041", gender: "male" },
      { position: 9, fullName: "Dinah Lance", studentId: "SUSL/FOC/4Y/2026/042", gender: "female" },
      { position: 10, fullName: "Shayera Hol", studentId: "SUSL/FOC/4Y/2026/043", gender: "female" },
      { position: 11, fullName: "J'onn J'onzz", studentId: "SUSL/FOC/4Y/2026/044", gender: "male" },
    ],
  },
  {
    id: "mock-team-5",
    team_name: "Titan XI",
    batch: "1st Year",
    captain_name: "Ethan Hunt",
    captain_email: "ethan@susl.ac.lk",
    captain_contact: "+94775678901",
    player_count: 11,
    female_count: 4,
    registered_at: "2026-02-01T12:00:00.000Z",
    group_name: "Group A",
    has_logo: false,
    players: [
      { position: 1, fullName: "Ethan Hunt (C)", studentId: "SUSL/FOC/1Y/2026/045", gender: "male" },
      { position: 2, fullName: "Luther Stickell", studentId: "SUSL/FOC/1Y/2026/046", gender: "male" },
      { position: 3, fullName: "Benji Dunn", studentId: "SUSL/FOC/1Y/2026/047", gender: "male" },
      { position: 4, fullName: "Ilsa Faust", studentId: "SUSL/FOC/1Y/2026/048", gender: "female" },
      { position: 5, fullName: "William Brandt", studentId: "SUSL/FOC/1Y/2026/049", gender: "male" },
      { position: 6, fullName: "Alan Hunley", studentId: "SUSL/FOC/1Y/2026/050", gender: "male" },
      { position: 7, fullName: "August Walker", studentId: "SUSL/FOC/1Y/2026/051", gender: "male" },
      { position: 8, fullName: "Grace Miller", studentId: "SUSL/FOC/1Y/2026/052", gender: "female" },
      { position: 9, fullName: "Paris Alana", studentId: "SUSL/FOC/1Y/2026/053", gender: "female" },
      { position: 10, fullName: "Solomon Lane", studentId: "SUSL/FOC/1Y/2026/054", gender: "male" },
      { position: 11, fullName: "Zola Mitsopolis", studentId: "SUSL/FOC/1Y/2026/055", gender: "female" },
    ],
  },
  {
    id: "mock-team-6",
    team_name: "Velocity Strikers",
    batch: "1st Year",
    captain_name: "Fiona Gallagher",
    captain_email: "fiona@susl.ac.lk",
    captain_contact: "+94776789012",
    player_count: 11,
    female_count: 5,
    registered_at: "2026-02-01T12:30:00.000Z",
    group_name: "Group B",
    has_logo: false,
    players: [
      { position: 1, fullName: "Fiona Gallagher (C)", studentId: "SUSL/FOC/1Y/2026/056", gender: "female" },
      { position: 2, fullName: "Lip Gallagher", studentId: "SUSL/FOC/1Y/2026/057", gender: "male" },
      { position: 3, fullName: "Ian Gallagher", studentId: "SUSL/FOC/1Y/2026/058", gender: "male" },
      { position: 4, fullName: "Debbie Gallagher", studentId: "SUSL/FOC/1Y/2026/059", gender: "female" },
      { position: 5, fullName: "Carl Gallagher", studentId: "SUSL/FOC/1Y/2026/060", gender: "male" },
      { position: 6, fullName: "Liam Gallagher", studentId: "SUSL/FOC/1Y/2026/061", gender: "male" },
      { position: 7, fullName: "Veronica Fisher", studentId: "SUSL/FOC/1Y/2026/062", gender: "female" },
      { position: 8, fullName: "Kevin Ball", studentId: "SUSL/FOC/1Y/2026/063", gender: "male" },
      { position: 9, fullName: "Mickey Milkovich", studentId: "SUSL/FOC/1Y/2026/064", gender: "male" },
      { position: 10, fullName: "Svetlana Yevgenivna", studentId: "SUSL/FOC/1Y/2026/065", gender: "female" },
      { position: 11, fullName: "Mandy Milkovich", studentId: "SUSL/FOC/1Y/2026/066", gender: "female" },
    ],
  },
  {
    id: "mock-team-7",
    team_name: "Royal Strikers",
    batch: "2nd Year",
    captain_name: "George Clark",
    captain_email: "george@susl.ac.lk",
    captain_contact: "+94777890123",
    player_count: 11,
    female_count: 3,
    registered_at: "2026-02-01T13:00:00.000Z",
    group_name: "Group C",
    has_logo: false,
    players: [
      { position: 1, fullName: "George Clark (C)", studentId: "SUSL/FOC/2Y/2026/067", gender: "male" },
      { position: 2, fullName: "William Turner", studentId: "SUSL/FOC/2Y/2026/068", gender: "male" },
      { position: 3, fullName: "Elizabeth Swann", studentId: "SUSL/FOC/2Y/2026/069", gender: "female" },
      { position: 4, fullName: "Jack Sparrow", studentId: "SUSL/FOC/2Y/2026/070", gender: "male" },
      { position: 5, fullName: "Hector Barbossa", studentId: "SUSL/FOC/2Y/2026/071", gender: "male" },
      { position: 6, fullName: "Joshamee Gibbs", studentId: "SUSL/FOC/2Y/2026/072", gender: "male" },
      { position: 7, fullName: "James Norrington", studentId: "SUSL/FOC/2Y/2026/073", gender: "male" },
      { position: 8, fullName: "Tia Dalma", studentId: "SUSL/FOC/2Y/2026/074", gender: "female" },
      { position: 9, fullName: "Davy Jones", studentId: "SUSL/FOC/2Y/2026/075", gender: "male" },
      { position: 10, fullName: "Anamaria Pirate", studentId: "SUSL/FOC/2Y/2026/076", gender: "female" },
      { position: 11, fullName: "Pintel Pirate", studentId: "SUSL/FOC/2Y/2026/077", gender: "male" },
    ],
  },
  {
    id: "mock-team-8",
    team_name: "Thunderbolts",
    batch: "2nd Year",
    captain_name: "Hannah Abbott",
    captain_email: "hannah@susl.ac.lk",
    captain_contact: "+94778901234",
    player_count: 11,
    female_count: 5,
    registered_at: "2026-02-01T13:30:00.000Z",
    group_name: "Group D",
    has_logo: false,
    players: [
      { position: 1, fullName: "Hannah Abbott (C)", studentId: "SUSL/FOC/2Y/2026/078", gender: "female" },
      { position: 2, fullName: "Harry Potter", studentId: "SUSL/FOC/2Y/2026/079", gender: "male" },
      { position: 3, fullName: "Ron Weasley", studentId: "SUSL/FOC/2Y/2026/080", gender: "male" },
      { position: 4, fullName: "Hermione Granger", studentId: "SUSL/FOC/2Y/2026/081", gender: "female" },
      { position: 5, fullName: "Neville Longbottom", studentId: "SUSL/FOC/2Y/2026/082", gender: "male" },
      { position: 6, fullName: "Ginny Weasley", studentId: "SUSL/FOC/2Y/2026/083", gender: "female" },
      { position: 7, fullName: "Luna Lovegood", studentId: "SUSL/FOC/2Y/2026/084", gender: "female" },
      { position: 8, fullName: "Fred Weasley", studentId: "SUSL/FOC/2Y/2026/085", gender: "male" },
      { position: 9, fullName: "George Weasley", studentId: "SUSL/FOC/2Y/2026/086", gender: "male" },
      { position: 10, fullName: "Cedric Diggory", studentId: "SUSL/FOC/2Y/2026/087", gender: "male" },
      { position: 11, fullName: "Cho Chang", studentId: "SUSL/FOC/2Y/2026/088", gender: "female" },
    ],
  },
  {
    id: "mock-team-9",
    team_name: "Code Breakers",
    batch: "3rd Year",
    captain_name: "Ian Malcolm",
    captain_email: "ian@susl.ac.lk",
    captain_contact: "+94779012345",
    player_count: 11,
    female_count: 3,
    registered_at: "2026-02-01T14:00:00.000Z",
    group_name: "Group A",
    has_logo: false,
    players: [
      { position: 1, fullName: "Ian Malcolm (C)", studentId: "SUSL/FOC/3Y/2026/089", gender: "male" },
      { position: 2, fullName: "Alan Grant", studentId: "SUSL/FOC/3Y/2026/090", gender: "male" },
      { position: 3, fullName: "Ellie Sattler", studentId: "SUSL/FOC/3Y/2026/091", gender: "female" },
      { position: 4, fullName: "John Hammond", studentId: "SUSL/FOC/3Y/2026/092", gender: "male" },
      { position: 5, fullName: "Dennis Nedry", studentId: "SUSL/FOC/3Y/2026/093", gender: "male" },
      { position: 6, fullName: "Ray Arnold", studentId: "SUSL/FOC/3Y/2026/094", gender: "male" },
      { position: 7, fullName: "Robert Muldoon", studentId: "SUSL/FOC/3Y/2026/095", gender: "male" },
      { position: 8, fullName: "Lex Murphy", studentId: "SUSL/FOC/3Y/2026/096", gender: "female" },
      { position: 9, fullName: "Tim Murphy", studentId: "SUSL/FOC/3Y/2026/097", gender: "male" },
      { position: 10, fullName: "Claire Dearing", studentId: "SUSL/FOC/3Y/2026/098", gender: "female" },
      { position: 11, fullName: "Owen Grady", studentId: "SUSL/FOC/3Y/2026/099", gender: "male" },
    ],
  },
  {
    id: "mock-team-10",
    team_name: "Matrix Warriors",
    batch: "3rd Year",
    captain_name: "Julia Roberts",
    captain_email: "julia@susl.ac.lk",
    captain_contact: "+94770123456",
    player_count: 11,
    female_count: 4,
    registered_at: "2026-02-01T14:30:00.000Z",
    group_name: "Group B",
    has_logo: false,
    players: [
      { position: 1, fullName: "Julia Roberts (C)", studentId: "SUSL/FOC/3Y/2026/100", gender: "female" },
      { position: 2, fullName: "Neo Anderson", studentId: "SUSL/FOC/3Y/2026/101", gender: "male" },
      { position: 3, fullName: "Trinity Matrix", studentId: "SUSL/FOC/3Y/2026/102", gender: "female" },
      { position: 4, fullName: "Morpheus Captain", studentId: "SUSL/FOC/3Y/2026/103", gender: "male" },
      { position: 5, fullName: "Agent Smith", studentId: "SUSL/FOC/3Y/2026/104", gender: "male" },
      { position: 6, fullName: "Cypher Reagan", studentId: "SUSL/FOC/3Y/2026/105", gender: "male" },
      { position: 7, fullName: "Tank Matrix", studentId: "SUSL/FOC/3Y/2026/106", gender: "male" },
      { position: 8, fullName: "Dozer Matrix", studentId: "SUSL/FOC/3Y/2026/107", gender: "male" },
      { position: 9, fullName: "Niobe Captain", studentId: "SUSL/FOC/3Y/2026/108", gender: "female" },
      { position: 10, fullName: "Persephone Matrix", studentId: "SUSL/FOC/3Y/2026/109", gender: "female" },
      { position: 11, fullName: "Oracle Matrix", studentId: "SUSL/FOC/3Y/2026/110", gender: "female" },
    ],
  },
  {
    id: "mock-team-11",
    team_name: "Legacy Kings",
    batch: "4th Year",
    captain_name: "Kevin Spacey",
    captain_email: "kevin@susl.ac.lk",
    captain_contact: "+94771122334",
    player_count: 11,
    female_count: 2,
    registered_at: "2026-02-01T15:00:00.000Z",
    group_name: "Group C",
    has_logo: false,
    players: [
      { position: 1, fullName: "Kevin Spacey (C)", studentId: "SUSL/FOC/4Y/2026/111", gender: "male" },
      { position: 2, fullName: "Keyser Soze", studentId: "SUSL/FOC/4Y/2026/112", gender: "male" },
      { position: 3, fullName: "Verbal Kint", studentId: "SUSL/FOC/4Y/2026/113", gender: "male" },
      { position: 4, fullName: "Dean Keaton", studentId: "SUSL/FOC/4Y/2026/114", gender: "male" },
      { position: 5, fullName: "Michael McManus", studentId: "SUSL/FOC/4Y/2026/115", gender: "male" },
      { position: 6, fullName: "Fred Fenster", studentId: "SUSL/FOC/4Y/2026/116", gender: "male" },
      { position: 7, fullName: "Todd Hockney", studentId: "SUSL/FOC/4Y/2026/117", gender: "male" },
      { position: 8, fullName: "Dave Kujan", studentId: "SUSL/FOC/4Y/2026/118", gender: "male" },
      { position: 9, fullName: "Edie Finneran", studentId: "SUSL/FOC/4Y/2026/119", gender: "female" },
      { position: 10, fullName: "Kobayashi Counsel", studentId: "SUSL/FOC/4Y/2026/120", gender: "male" },
      { position: 11, fullName: "Rachel Keaton", studentId: "SUSL/FOC/4Y/2026/121", gender: "female" },
    ],
  },
  {
    id: "mock-team-12",
    team_name: "Quantum Strikers",
    batch: "4th Year",
    captain_name: "Laura Croft",
    captain_email: "laura@susl.ac.lk",
    captain_contact: "+94772233445",
    player_count: 11,
    female_count: 5,
    registered_at: "2026-02-01T15:30:00.000Z",
    group_name: "Group D",
    has_logo: false,
    players: [
      { position: 1, fullName: "Laura Croft (C)", studentId: "SUSL/FOC/4Y/2026/122", gender: "female" },
      { position: 2, fullName: "Nathan Drake", studentId: "SUSL/FOC/4Y/2026/123", gender: "male" },
      { position: 3, fullName: "Victor Sullivan", studentId: "SUSL/FOC/4Y/2026/124", gender: "male" },
      { position: 4, fullName: "Elena Fisher", studentId: "SUSL/FOC/4Y/2026/125", gender: "female" },
      { position: 5, fullName: "Chloe Frazer", studentId: "SUSL/FOC/4Y/2026/126", gender: "female" },
      { position: 6, fullName: "Samuel Drake", studentId: "SUSL/FOC/4Y/2026/127", gender: "male" },
      { position: 7, fullName: "Charlie Cutter", studentId: "SUSL/FOC/4Y/2026/128", gender: "male" },
      { position: 8, fullName: "Nadine Ross", studentId: "SUSL/FOC/4Y/2026/129", gender: "female" },
      { position: 9, fullName: "Rafe Adler", studentId: "SUSL/FOC/4Y/2026/130", gender: "male" },
      { position: 10, fullName: "Gabriel Roman", studentId: "SUSL/FOC/4Y/2026/131", gender: "male" },
      { position: 11, fullName: "Marisa Chase", studentId: "SUSL/FOC/4Y/2026/132", gender: "female" },
    ],
  },
];
